# Load environment variables from .env file
# Docker Compose automatically reads from .env in the same directory

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/media/ksp/ksp_app/ce-it-hub-hackathon-2025
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ENGINE=django.db.backends.postgresql
      - NETWORK_HOST=${NETWORK_HOST} # auto-detected by set_network_ip.sh
    entrypoint: ["/bin/bash", "-c", "if [ \"$DEBUG\" = \"True\" ]; then exec uv run manage.py runserver 0.0.0.0:8000; else exec uv run gunicorn ksp.wsgi:application --bind 0.0.0.0:8000; fi"]

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./staticfiles:/media/ksp/ksp_app/ce-it-hub-hackathon-2025/app/staticfiles
      - ./static:/media/ksp/ksp_app/ce-it-hub-hackathon-2025/app/static
      - ./media:/media/ksp/ksp_app/ce-it-hub-hackathon-2025/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
