# Generated by Django 5.2.1 on 2025-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="qr_code_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
