# Generated by Django 5.2.1 on 2025-05-14 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warehouse', '0003_rack_qr_code_uuid_room_qr_code_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemshelfassignment',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='itemshelfassignment',
            name='remove_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='warehouse_i_name_c0bc65_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['category'], name='warehouse_i_categor_07433e_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['manufacturer'], name='warehouse_i_manufac_461d84_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['expiration_date'], name='warehouse_i_expirat_1bd2d0_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(fields=['item'], name='warehouse_i_item_id_5ed927_idx'),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(fields=['shelf'], name='warehouse_i_shelf_i_cae1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(
                fields=['add_date'], name='warehouse_i_add_dat_88c768_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(
                fields=['remove_date'], name='warehouse_i_remove__b37474_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(
                fields=['shelf', 'remove_date'], name='warehouse_i_shelf_i_550f56_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='itemshelfassignment',
            index=models.Index(
                fields=['item', 'remove_date'], name='warehouse_i_item_id_564bac_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['room'], name='warehouse_r_room_id_39d0db_idx'),
        ),
        migrations.AddIndex(
            model_name='shelf',
            index=models.Index(fields=['rack'], name='warehouse_s_rack_id_8cd568_idx'),
        ),
    ]
