site_name: Krwinka Inventory Management
repo_url: https://github.com/agoralewski/ce-it-hub-hackathon-2025
site_dir: '../generated/en'
theme:
  language: en
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.footer
nav:
- Welcome: index.md
- Deployment: deploy.md
- Maintenance: maintenance.md
- Features: features.md
- User Guide: user_guide.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/agoralewski/ce-it-hub-hackathon-2025
  alternate:
  - name: English
    link: ce-it-hub-hackathon-2025/en/
    lang: en
  - name: Polski
    link: ce-it-hub-hackathon-2025/pl/
    lang: pl
markdown_extensions:
- toc:
    permalink: "#"
plugins:
- mermaid2
- search:
    lang: en
