name: Build and Deploy Documentation

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - publish-docs

# security: restrict permissions for CI jobs.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
 
      - name: Set up Python
        run: uv python install
 
      - name: Install deps
        run: uv sync
 
      # Build English documentation
      - name: Build English docs
        run: uv run mkdocs build -f ./docs/en/mkdocs.yml -d ./site/en
      
      # Build Polish documentation
      - name: Build Polish docs
        run: uv run mkdocs build -f ./docs/pl/mkdocs.yml -d ./site/pl
      
      # Create index.html in the root to redirect to English or based on browser language
      - name: Create root index.html
        run: |
          mkdir -p ./site
          cat > ./site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Documentation Redirect</title>
            <script>
              // Get the browser language
              var lang = navigator.language || navigator.userLanguage;
              lang = lang.split('-')[0]; // Take just the primary language tag
              
              // Redirect based on language or default to English
              if (lang === 'pl') {
                window.location.href = '/pl/';
              } else {
                window.location.href = '/en/';
              }
            </script>
            <meta http-equiv="refresh" content="0; url=/en/">
          </head>
          <body>
            <p>Redirecting to documentation...</p>
            <p><a href="/en/">Click here if you are not redirected automatically</a></p>
          </body>
          </html>
          EOF

      # Upload docs as an artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Deploy the artifact to GitHub pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4