name: Deploy EN Docs
on:
  push:
    branches:
      - main
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install deps
        run: uv sync

      - name: Deploy docs
        run: cd en && uv run mkdocs gh-deploy
